### PR TITLE
Setup eslint, prettier, and husky

### PR DESCRIPTION
**Pull request by Hanan795**

### CODE REVIEW

**Comment by Jood80** [comment]
Lovely :sparkles: 
just add these configurations into your `.circleci/ config.yml` file 
```yml
version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
```

**Review by Jood80 — APPROVED** [review]
Lovely :sparkles: 
just add these configurations into your `.circleci/ config.yml` file 
```yml
version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
```

**Comment by Hanan795** [comment]
> Lovely 
> you only need to fix your CI, for that just add these configurations into your `.circleci/ config.yml` file
> 
> ```yaml
> version: 2.1
> orbs:
>   node: circleci/node@3.0.0
> jobs:
>   build-and-test:
>     executor:
>       name: node/default
>     steps:
>       - checkout
>       - node/install-packages
>       - run:
>           command: npm run test
> workflows:
>   build-and-test:
>     jobs:
>       - build-and-test
> ```
> 
> if all tests pass, you may merge

Unfortunately, I can't do that. beacause I start in it before circleci, I can't commit changes from another branches, since problems in style related to husky.

**Comment by Jood80** [comment]
> Unfortunately, I can't do that. beacause I start in it before circleci, I can't commit changes from another branches, since problems in style related to husky.

Ok I understand your point, in that case, don't forget to create a new issue for that :v:

**Pull request merged**
